### ISSUE TITLE
Failed to compile project after upgrading to 6.0.0

### ISSUE THREAD

**Issue by asfdfdfd** [Kodein-Framework/Kodein-DI#165]
./gradlew assembleDevelopmentDebug

failed on kapt stage with error message:

```
Work/mirrorai/Source/mirrorai-android/app/src/main/java/com/mirrorai/app/fragments/signup/SignUpMvpPresenter.java:63: error: static import only from classes and interfaces
import static org.kodein.di.TypesKt.TT;
^/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/src/main/java/com/mirrorai/app/fragments/signup/SignUpMvpPresenter.java:70: error: cannot find symbol
    private final DKodein kodeinDirect = MirrorApplication.getInstance().getKodeinDirect();
                  ^
  symbol:   class DKodein
  location: class SignUpMvpPresenter/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/EmojisFragmentMvpPresenter.java:14: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/emojimaker/RateFaceMvpPresenter.java:16: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/emojimaker/navigation/EmojiStartupNavigationMvpPresenter.java:19: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/emojimaker/navigation/EmojiUpdateNavigationMvpPresenter.java:16: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/SelectLocaleMvpPresenter.java:18: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/SettingsFragment.java:27: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/EmojisNavigationFragment.java:72: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/MainNavigationMvpPresenter.java:24: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/WhatsAppPacksListMvpPresenter.java:20: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/MainNavigationFragment.java:51: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/keyboard/KeyboardInstallFragmentMvpPresenter.java:11: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/main/share/ShareMvpPresenter.java:29: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/StickerShareService.java:14: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/fragments/instagram/AddStickerToStoriesMvpPresenter.java:19: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/StickerSuggestionsService.java:23: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/activities/MainActivityMvpPresenter.java:21: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/workers/DisplayReminderLocalNotification.java:16: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/workers/DelayDisplayReminderLocalNotificationWorker.java:15: error: cannot find symbol
    public org.kodein.di.Kodein getKodein() {
                        ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/views/keyboard/KeyboardView.java:60: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/views/keyboard/KeyboardEmojisListView.java:23: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/mirrorai/app/views/keyboard/KeyboardStickersWithToolbarView.java:26: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di/Users/asfdfdfd/Work/mirrorai/Source/mirrorai-android/app/build/tmp/kapt3/stubs/developmentDebug/com/bumptech/glide/MirrorGlideLocalizedEmojiDataFetcher.java:14: error: cannot find symbol
    private final org.kodein.di.Kodein getKodein() {
                               ^
  symbol:   class Kodein
  location: package org.kodein.di

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDevelopmentDebugKotlin'.
> There was a failure while executing work items
   > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
      > java.lang.reflect.InvocationTargetException (no error message)
```
Some of these files are Java, but mostly Kotlin.

I use Kotln 1.3.10.

**Comment by igorwojda** [comment]
Bunch of the stuff seems to be missing including `KodeinAware` interface

**Comment by mkobit** [comment]
I'm seeing this too. A few things I notice between 5.3.0 (https://jcenter.bintray.com/org/kodein/di/kodein-di-generic-jvm/5.3.0/) and 6.0.0 (https://jcenter.bintray.com/org/kodein/di/kodein-di-generic-jvm/6.0.0/)

- No `.module` published for 6.0.0
- POM has different `<scope>` for transitive dependency on `kodein-di-core-jvm`
    * 5.3.0

        ```xml
        <?xml version="1.0" encoding="UTF-8"?>
        <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <modelVersion>4.0.0</modelVersion>
          <groupId>org.kodein.di</groupId>
          <artifactId>kodein-di-generic-jvm</artifactId>
          <version>5.3.0</version>
          <dependencies>
            <dependency>
              <groupId>org.kodein.di</groupId>
              <artifactId>kodein-di-core-jvm</artifactId>
              <version>5.3.0</version>
              <scope>compile</scope>
            </dependency>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-stdlib-jdk7</artifactId>
              <version>1.2.70</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </project>
        ```

    * 6.0.0

        ```xml
        <?xml version="1.0" encoding="UTF-8"?>
        <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <modelVersion>4.0.0</modelVersion>
          <groupId>org.kodein.di</groupId>
          <artifactId>kodein-di-generic-jvm</artifactId>
          <version>6.0.0</version>
          <dependencies>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-stdlib-jdk7</artifactId>
              <version>1.3.0</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>org.kodein.di</groupId>
              <artifactId>kodein-di-core</artifactId>
              <version>6.0.0</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </project>
        ```
* TODO: I haven't dove in depth of the JARs to see what differences are there yet

**Comment by SalomonBrys** [comment]
THis is due to the new multiplatform build system.

I'll investigate and try to correct.

**Comment by SalomonBrys** [comment]
In the meantime, manually adding the dependency "org.kodein.di:kodein-di-core-jvm:6.0.0" should correct the issue

**Comment by igorwojda** [comment]
Confirm - all classes are present after manually adding this dependency. 
Thanks for a quick help.

**Comment by SalomonBrys** [comment]
This is due to several issues in new mpp deployment: 

https://youtrack.jetbrains.com/issue/KT-28482
https://youtrack.jetbrains.com/issue/KT-28355
https://youtrack.jetbrains.com/issue/KT-27059

Still working on this for 6.0.1

**Comment by igorwojda** [comment]
All upvoted, hope this helps.

**Comment by JorgeCastilloPrz** [comment]
I got the same problem, this issue saved me :)

**Comment by SalomonBrys** [comment]
This should be corrected in version 6.0.1. All POMs should be fixed :)
