### ISSUE TITLE
Android apps using using Jetpack Compose 1.0.0-beta07+ crash with Kodein 7.5.0

### ISSUE THREAD

**Issue by Galaxer** [Kodein-Framework/Kodein-DI#372]
I updated an Android project from Jetpack Compose version 1.0.0-beta06 to 1.0.0-beta08 and the app crashes.

According to the release notes for Compose 1.0.0-beta07 third party libs will need to be recompiled:

```
Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)
```
This is the exception I'm encountering.

https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.0.0-beta07

Please update `kodein-di-framework-compose:7.5.0` to support the latest version of Compose (1.0.0-beta08 currently)

**Comment by romainbsl** [comment]
Compose beta08 is based on Kotlin 1.5, you should consider using Kodein-DI 7.6 that is also built on top of Kotlin 1.5.
(FYI 7.5 is based on 1.4.32)

**Comment by romainbsl** [comment]
Kodein-DI 7.5.1 is building, publication will follow: https://github.com/Kodein-Framework/Kodein-DI/actions/runs/902244888

Also, I've updated the docs to show a compatibility table between DI and Compose with the proper Kotlin version applied.
https://docs.kodein.org/kodein-di/7.6/framework/compose.html.
